name: Build and Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*' # version Tag push use release workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: tubone24/setup-nim-action@v1.0.1
      - name: Install Dependencies
        run: nimble install -d --accept
      - name: Build
        run: nimble build -d:release
      - name: Test
        env:
          TZ: Asia/Tokyo
        run: nimble test
