name: Build and Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*' # version Tag push use release workflow

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1.5.1
      - name: Install Dependencies
        run: nimble install -d --accept
      - name: Set secret file
        env:
          SECRET_FILE: ${{ secrets.SECRET_FILE }}
        run: |
          echo $SECRET_FILE > base64.txt
          nim c --run scripts/createBase64ToFile.nim
      - name: Build
        run: nimble build -d:release
      - name: Test
        env:
          TZ: Asia/Tokyo
        run: nimble test
